"""初始化SQLite数据库

Revision ID: ceae634b9a87
Revises: 
Create Date: 2025-12-04 16:37:56.535027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceae634b9a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='分类别名'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='分类描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('t_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_category_name'), ['name'], unique=False)

    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=21), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='角色代码'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='角色名称'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='角色描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_role_code'), ['code'], unique=True)

    op.create_table('t_site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=64), nullable=False, comment='网站名称'),
    sa.Column('domain', sa.String(length=128), nullable=False, comment='网站域名'),
    sa.Column('keywords', sa.String(length=256), nullable=True, comment='META关键字'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='MWTA描述'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_site_site_name'), ['site_name'], unique=False)

    op.create_table('t_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='标签名'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_tag_name'), ['name'], unique=False)

    op.create_table('t_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleid', sa.Integer(), nullable=True),
    sa.Column('permissionid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissionid'], ['t_permission.id'], ),
    sa.ForeignKeyConstraint(['roleid'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_role_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_role_permission_permissionid'), ['permissionid'], unique=False)
        batch_op.create_index(batch_op.f('ix_t_role_permission_roleid'), ['roleid'], unique=False)

    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='登录名'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='用户昵称'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('roleid', sa.Integer(), nullable=True, comment='角色ID'),
    sa.Column('registertime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('status', sa.Boolean(), server_default=sa.text('(True)'), nullable=True, comment='用户状态'),
    sa.ForeignKeyConstraint(['roleid'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_user_username'), ['username'], unique=True)

    op.create_table('t_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False, comment='页面标题'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='页面别名'),
    sa.Column('authorid', sa.Integer(), nullable=True, comment='作者ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('publishtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='修改时间'),
    sa.Column('status', sa.Enum('published', 'draft', name='pagestatus'), nullable=True, comment='页面状态'),
    sa.ForeignKeyConstraint(['authorid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('t_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_page_title'), ['title'], unique=False)

    op.create_table('t_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False, comment='文章标题'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='标题别名'),
    sa.Column('authorid', sa.Integer(), nullable=True, comment='作者ID'),
    sa.Column('excerpt', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('categoryid', sa.Integer(), nullable=True, comment='分类ID'),
    # 将image字段改为tag字段
    sa.Column('tag', sa.String(length=500), nullable=True, comment='标签'),  # 原字段名为image
    sa.Column('publishtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='修改时间'),
    sa.Column('counter', sa.Integer(), nullable=True, comment='阅读计数'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='文章状态'),
    sa.ForeignKeyConstraint(['authorid'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['categoryid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_post_title'), ['title'], unique=False)

    op.create_table('t_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postid', sa.Integer(), nullable=True, comment='文章id'),
    sa.Column('content', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('author', sa.String(length=64), nullable=False, comment='用户昵称'),
    sa.Column('author_email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('author_IP', sa.String(length=128), nullable=False, comment='IP'),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='发表时间'),
    sa.Column('parentid', sa.Integer(), nullable=True, comment='父评论id'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='评论状态'),
    sa.ForeignKeyConstraint(['parentid'], ['t_comment.id'], ),
    sa.ForeignKeyConstraint(['postid'], ['t_post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_IP'),
    sa.UniqueConstraint('author_email')
    )
    op.create_table('t_post_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=True),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['t_post.id'], ),
    sa.ForeignKeyConstraint(['tagid'], ['t_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('t_post_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_post_tag_postid'), ['postid'], unique=False)
        batch_op.create_index(batch_op.f('ix_t_post_tag_tagid'), ['tagid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_post_tag_tagid'))
        batch_op.drop_index(batch_op.f('ix_t_post_tag_postid'))

    op.drop_table('t_post_tag')
    op.drop_table('t_comment')
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_post_title'))

    op.drop_table('t_post')
    with op.batch_alter_table('t_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_page_title'))

    op.drop_table('t_page')
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_user_username'))

    op.drop_table('t_user')
    with op.batch_alter_table('t_role_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_role_permission_roleid'))
        batch_op.drop_index(batch_op.f('ix_t_role_permission_permissionid'))

    op.drop_table('t_role_permission')
    with op.batch_alter_table('t_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_tag_name'))

    op.drop_table('t_tag')
    with op.batch_alter_table('t_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_site_site_name'))

    op.drop_table('t_site')
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_role_code'))

    op.drop_table('t_role')
    op.drop_table('t_permission')
    with op.batch_alter_table('t_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_category_name'))

    op.drop_table('t_category')
    # ### end Alembic commands ###
