"""更新表t_post

Revision ID: d5c8982d58c7
Revises: ceae634b9a87
Create Date: 2025-12-05 22:35:36.938612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c8982d58c7'
down_revision = 'ceae634b9a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
