"""修复Post模型字段与关系名冲突

Revision ID: ffd34281a328
Revises: d5c8982d58c7
Create Date: 2025-12-05 23:02:49.961545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd34281a328'
down_revision = 'd5c8982d58c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True, comment='标签'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
